export enum Theme {
    TaylorSwift = 'Taylor Swift',
    Bzrp = 'bzrp',
    Duki = 'Duki',
    MariaBecerra = 'Maria Becerra',
    YSYA = 'YSY A',
    Tini = 'Tini',
    NickiNicole = 'Nicki Nicole',
    Wos = 'Wos',
    Louta = 'Louta',
    Trueno = 'Trueno',
    Lali = 'Lali',
    AbelPintos = 'Abel Pintos',
    Cerati = 'Cerati',
    SodaStereo = 'Soda Stereo',
    LosRedondos = 'Los redondos',
    LaRenga = 'La Renga',
    CharlyGarcia = 'Charly Garcia',
    Iorio = 'Iorio',
    CristianCastro = 'Cristian Castro',
    DuaLipa = 'Dua Lipa',
    Robleis = 'Robleis',
    EdSheeran = 'Ed Sheeran'
}
export const themes: Theme[] = [
    Theme.TaylorSwift,
    Theme.Bzrp,
    Theme.Duki,
    Theme.MariaBecerra,
    Theme.YSYA,
    Theme.Tini,
    Theme.NickiNicole,
    Theme.Wos,
    Theme.Louta,
    Theme.Trueno,
    Theme.Lali,
    Theme.AbelPintos,
    Theme.Cerati,
    Theme.SodaStereo,
    Theme.LosRedondos,
    Theme.LaRenga,
    Theme.CharlyGarcia,
    Theme.Iorio,
    Theme.CristianCastro,
    Theme.DuaLipa,
    Theme.Robleis,
    Theme.EdSheeran
].sort((a, b) => a.localeCompare(b));