export enum Theme {
    TaylorSwift = 'Taylor Swift',
    Bzrp = 'bzrp',
    Duki = 'Duki',
    MariaBecerra = 'Maria Becerra',
    YSYA = 'YSY A',
    Tini = 'Tini',
    NickiNicole = 'Nicki Nicole',
    Wos = 'Wos',
    Louta = 'Louta',
    Trueno = 'Trueno',
    Lali = 'Lali',
    AbelPintos = 'Abel Pintos',
    Cerati = 'Cerati',
    SodaStereo = 'Soda Stereo',
    LosRedondos = 'Los redondos',
    LaRenga = 'La Renga',
    CharlyGarcia = 'Charly Garcia',
    Iorio = 'Iorio',
    CristianCastro = 'Cristian Castro',
}